### ISSUE TITLE
Batoto changes.

### ISSUE THREAD

**Issue by XellossMetallium** [MangaRack/mangarack#34]
New announcement on Batoto: registration will be required to access the site and the reader will be modified to manage bots and crawling sw. 
Here the link: http://bato.to/forums/topic/23703-moving-forward-upcoming-changes-and-schedules

I suppose this will require updates on mangarack side (if technically possible), both for login and to limit the number of simultaneous accesses.

**Comment by Deathspike** [comment]
I understand their position. I will have to track their progress and see happens. On our side:

* We will need to migrate to a new URL scheme.
* We will need to add authentication credentials to MangaRack.
* We will need to start using headless browsers to run browser-side JavaScript.
* We will need to update the scraping code to accommodate the changes.

Instead of running a headless browser, I may try to emulate expected behavior first. Because:

* Emulation of expected behavior keeps the requirements down and is thus less expensive.
* It will work in an environment where running a headless browser is impossible (Android/iOS/WP).
* ... But, depending on the amount of changes on their side, we need to match, too.

I'm going to wait it out a little bit and see which approach they'll be taking.

That means, during that time, MangaRack is not entirely compatible. Sorry. Hope you understand :+1:

**Comment by XellossMetallium** [comment]
Batoto admin position makes sense.. if they actually take the load of
other (and there are many) reading sites that crawl their releases all
the time, all the "support to scanlators" philosophy would be
invalidated.
No problem at all here., we will catch up when possible :)
Actually I wouldn't even mind a mangarack slowed down to "almost human
reading speed" to lessen the load on their server, if this could help.
Thank you!

**Comment by qoyyim** [comment]
seems now kissmanga also banned bot too

**Comment by Deathspike** [comment]
A minor update on this issue to all those who are subscribed to this issue:

I have completed support for Bato.to credentials in the 4.0 branch. It is currently undergoing some additional testing, but it seems to be pretty stable. The 4.0 branch will soon replace the current 3.0 branch. Your configurations will have to be updated, but expect this support/change to be coming this weekend, or the next.

**Comment by XellossMetallium** [comment]
Awesome! If you need help with testing feel free to ask!

Il giorno Gio 26 Nov 2015 21:21 Roel van Uden <notifications@github.com> ha
scritto:

**Comment by qoyyim** [comment]
cool :+1:

**Comment by Deathspike** [comment]
`4.0.0` is live. Please refer to the updated instructions and migration guide.
